version: '3'
services:
  node:
    image: node:16.13.1
    working_dir: /app/web
    volumes:
      - $PWD/web:/app/web
    command: sh -c "npm install && npm run build"

  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather-tool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  scala:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - $PWD:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres