FROM hseeberger/scala-sbt:17.0.2_1.6.2_2.13.8 as build

WORKDIR /app
COPY . /app

RUN sbt clean assembly

FROM amazoncorretto:17-alpine

COPY --from=build /app/target/scala-2.13/app.jar /app.jar

CMD ["java", "-jar", "app.jar"]
