# fly.toml app configuration file generated for weather-tool on 2023-05-12T22:54:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weather-tool"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[mounts]]
  source = "data_volume"
  destination = "/data"

[scale]
  count = 1
  idle_timeout = 0

#[[services]]
#  internal_port = 8080
#  protocol = "tcp"

#[[services.ports]]
#  handlers = ["http"]
#  port = "80"

#[[services.ports]]
#  handlers = ["tls", "http"]
#  port = "443"

#[[services.tcp_checks]]
#  interval = 10000
#  timeout = 2000